version: '3.9'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    env_file: ./.env.local
    environment:
      - NODE_ENV=local
      - POSTGRES_PORT=5432
    depends_on:
      dbserver:
        condition: service_healthy

  dbserver:
    image: postgres:latest
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
